
export const USER_ADD_NEW_TASK_REQUEST = "USER_ADD_NEW_TASK_REQUEST";
export const USER_ADD_NEW_TASK_SUCCESS = "USER_ADD_NEW_TASK_SUCCESS";
export const USER_ADD_NEW_TASK_FAILURE = "USER_ADD_NEW_TASK_FAILURE";